dist: xenial
language: rust
rust:
  - nightly

cache:
  - apt
  - directories:
    - $HOME/qemu

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup target add riscv64imac-unknown-none-elf || true

before_script:
  - bash -e third_party/travis-qemu.sh
  - export PATH=$PATH:$HOME/qemu/bin

script:
  - make target/riscv64imac-unknown-none-elf/release/rvirt
  - make target/riscv64imac-unknown-none-elf/release/rvirt-bare-metal
  - make qemu

notifications:
  email:
    on_success: never
